[package]
name = "hygge"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/developing-today/hygge"
readme = "README.md"
description = """
Hygge, a KDL builder, rudimentary serializer 🥣
"""

[dependencies]
kdl = "3.0.0"
